### ISSUE TITLE
Provide the ability to use custom click handler

### ISSUE THREAD

**Issue by DerGuteWolf** [sergey-rossokha/MapClusterer#2]
It would be nice, if one could provide a custom click handler, esp. for the last zoom level.
I have the problem in out application that a lot times there are some markers at exact the same coordinates. With MarkeClustererPlus on GoogleMaps (http://code.google.com/p/google-maps-utility-library-v3/wiki/Libraries#MarkerClustererPlus) I show the cluster marker also at the max zoom level and on click I display an InfoWindow listing the info from the marker at this spot (yes, I could filter the marker before and modify them but in this way I think its easier, because it decouples markers from clustering).

**Comment by sergey-rossokha** [comment]
Thanks you a lot! I will add handler for the click event tomorrow. Sorry for that, I can't add it right now, I have a lot of work for today :( .

**Comment by sergey-rossokha** [comment]
Event handler has been added in 2012
